/* eslint-disable max-len */
export default {
  timelines: [
    {
      id: 1,
      startAt: '00:00:00',
      respawnId: 0,
      complexity: 0,
      direction: 'top',
      endAt: '00:28:44',
      events: [
        {
          type: 'Event',
          timecode: '0:02:00',
          episode: '1A',
          episodeRelativeTC: '0:02:00',
          description: 'Subaru spawns next to the Lugnica fountain.',
        },
        {
          id: 1,
          type: 'RespawnPoint',
          timecode: '0:03:30',
          episode: '1A',
          episodeRelativeTC: '0:02:00',
          description: 'Subaru talks to a merchant.',
        },
        {
          type: 'Event',
          timecode: '0:05:30',
          episode: '1A',
          episodeRelativeTC: '0:05:30',
          description: 'Subaru encounters three thugs in a dark alleyway. Emilia, who were chasing Felt, scares away the thugs and heals Subaru.',
        },
        {
          type: 'Event',
          timecode: '0:27:16',
          episode: '1B',
          episodeRelativeTC: '0:02:00',
          description: "Subaru and Emilia arrive at Rom's tavern but Subaru decides to enter alone.",
        },
        {
          type: 'Death',
          timecode: '0:28:44',
          episode: '1B',
          episodeRelativeTC: '0:04:16',
          description: 'A woman hidden in the dark stabs Subaru. After hearing strange noises coming from the inside, Emilia enters the tavern and gets stabbed.',
        },
      ],
    },
    {
      id: 2,
      startAt: '00:31:16',
      respawnId: 1,
      complexity: 1,
      direction: 'top',
      endAt: '0:42:09',
      events: [
        {
          type: 'Event',
          timecode: '0:01:44',
          episode: '1B',
          episodeRelativeTC: '0:06:00',
          description: "Subaru doesn't understand what happened but he hurries to find Emilia. In the same alleyway, he encounters the three thugs but this time he kicks the shit out of them and rushes to the tavern.",
        },
        {
          type: 'Event',
          timecode: '0:05:45',
          episode: '1B',
          episodeRelativeTC: '0:11:45',
          description: "Subaru enters the tavern and negotiates with Rom, Felt and Elsa to buy back Emilia's badge.",
        },
        {
          type: 'Death',
          timecode: '0:10:53',
          episode: '1B',
          episodeRelativeTC: '0:22:38',
          description: 'After winning the negotiations, Subaru reveals his intentions to give back the badge to Emilia. Elsa does not agree and kills Rom, Felt and Subaru.',
        },
      ],
    },
    {
      id: 3,
      startAt: '00:31:16',
      respawnId: 1,
      complexity: 2,
      direction: 'top',
      endAt: '0:42:09',
      events: [
        {
          type: 'Event',
          timecode: '0:01:44',
          episode: '1B',
          episodeRelativeTC: '0:06:00',
          description: '????',
        },
        {
          type: 'Death',
          timecode: '0:10:53',
          episode: '1B',
          episodeRelativeTC: '0:22:38',
          description: 'Subaru is stabbed by the three thugs.',
        },
      ],
    },
    {
      id: 4,
      startAt: '01:36:16',
      respawnId: 1,
      complexity: 3,
      direction: 'top',
      endAt: '02:42:09',
      events: [
        {
          type: 'Event',
          timecode: '00:05:00',
          episode: '',
          episodeRelativeTC: '00:03:00',
          description: 'Subaru encounters the three thugs and screams for help.',
        },
        {
          type: 'Event',
          timecode: '00:10:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: 'Subaru, Emilia, Rom, Felt and Reinhart fight Elsa.',
        },
        {
          id: 2,
          type: 'RespawnPoint',
          timecode: '00:20:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: 'Subaru wakes up with Rem and Ram at his bedside.',
        },
        {
          type: 'Event',
          timecode: '00:30:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: 'Roswaal grants a wish to Subaru for helping Emilia. He decides to become a butler for the mansion.',
        },
        {
          type: 'Event',
          timecode: '00:40:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: 'During four complete days, Subaru learns to help Rem and Ram in their daily tasks.',
        },
        {
          type: 'Event',
          timecode: '00:50:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: '???????????? Subaru and Rem go to a close village',
        },
        {
          type: 'Death',
          timecode: '01:06:09',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: 'Subaru inexplicably dies in his sleep. Spoiler: He later understands that he had been cursed.',
        },
      ],
    },
    {
      id: 5,
      startAt: '00:31:16',
      respawnId: 2,
      complexity: 1,
      direction: 'top',
      endAt: '0:42:09',
      events: [
        {
          type: 'Event',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: 'Subaru becomes a butler once again to do the same actions has the previous loop and understand who kill him.',
        },
        {
          type: 'Event',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: 'Emilia teaches Subaru to read and write. After the lesson, Subaru asks Emilia for a date in the village.',
        },
        {
          type: 'Death',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: 'In the middle of the night, Subaru feels sick and get out of his room. He hears chains in the distance and, without being able to retaliate, he is killed.',
        },
      ],
    },
    {
      id: 6,
      startAt: '00:31:16',
      respawnId: 2,
      complexity: 2,
      direction: 'top',
      endAt: '0:42:09',
      events: [
        {
          type: 'Event',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: 'This time, Subaru becomes a guest to gather informations about the killer.',
        },
        {
          type: 'Event',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: "After four days, Subaru leaves Roswaal's mansion to wait for the killer in the forest.",
        },
        {
          type: 'Death',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: "Rem attacks Subaru because he stinks the Witch. She cuts Subaru's right leg and questions him. Ram finishes him off by cutting his throat.",
        },
      ],
    },
    {
      id: 7,
      startAt: '00:31:16',
      respawnId: 2,
      complexity: 3,
      direction: 'top',
      endAt: '0:42:09',
      events: [
        {
          type: 'Event',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: 'Subaru wakes up but is too shocked by the previous loop to move.',
        },
        {
          type: 'Event',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: 'Beatrice visits Subaru in his room. He asks for her protection until the morning of the fifth day.',
        },
        {
          type: 'Event',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: "On the morning of the 5th day, Subaru leaves Beatrice's library and finds Rem dead because of a curse.",
        },
        {
          type: 'Death',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: 'Ram chases Subaru outside the mansion to kill him. Beatrice is still protection Subaru but he jumps off the cliff.',
        },
      ],
    },
    {
      id: 8,
      startAt: '00:31:16',
      respawnId: 2,
      complexity: 4,
      direction: 'top',
      endAt: '0:42:09',
      events: [
        {
          type: 'Event',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: 'Subaru becomes a butler for the third time.',
        },
        {
          type: 'Event',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: "Subaru struggles to hide his emotions and bursts into tears on Emilia's knees.",
        },
        {
          type: 'Event',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: 'Pack teaches Subaru how to use his mana (kind of).',
        },
        {
          type: 'Event',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: '???????????? Subaru and Rem go to the village',
        },
        {
          type: 'Event',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: 'Subaru and Rem quickly returns to the village because Beatrice tells him that the curse comes from it.',
        },
        {
          type: 'Event',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: 'Subaru protects Rem and is severely wounded.',
        },
        {
          type: 'Event',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: 'To prevent Subaru from dying of his many curses, Rem goes alone in the forest to kill all the beast ([name of the beast here]). Ram and Subaru join her and Roswaal saves them.',
        },
        {
          type: 'Event',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: '???? Emilia, Subaru, Rem and Roswaal go to Lugnica. (details ?)',
        },
        {
          type: 'Event',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: 'The next day, Emilia and Roswaal return to Lugnica. Subaru goes to the capital even though Emilia said him not to.',
        },
        {
          type: 'MangaEvent',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: 'Aldebaran confesses to Subaru that he comes from Japan too.',
        },
        {
          type: 'Event',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: 'Subaru fights with Julius.',
        },
        {
          id: 3,
          type: 'RespawnPoint',
          timecode: '00:05:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: 'Subaru and Rem talk to the apple vendor.',
        },
        {
          type: 'Event',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: '?????? ? ',
        },
        {
          type: 'Death',
          timecode: '00:11:01',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: 'Looking for Emilia, Subaru finds a secret corridor in the mansion and is freezed to death by Pack.',
        },
      ],
    },
    {
      id: 9,
      startAt: '00:31:16',
      respawnId: 3,
      complexity: 1,
      direction: 'top',
      endAt: '0:42:09',
      events: [
        {
          type: 'Event',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: '???',
        },
        {
          type: 'Death',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: 'Subaru arrives at the mansion, an enourmous creature emerges from the mansion, freezes and beheads Subaru.',
        },
      ],
    },
    {
      id: 10,
      startAt: '00:31:16',
      respawnId: 3,
      complexity: 2,
      direction: 'top',
      endAt: '0:42:09',
      events: [
        {
          type: 'Event',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: '???',
        },
        {
          type: 'Event',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: 'Subaru tries to tell Emilia about his ability to respawn, but the Witch of Envy kills her.',
        },
        {
          type: 'Death',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: 'Subaru is attacked by the Cult, Pack kills everyone.',
        },
      ],
    },
    {
      id: 11,
      startAt: '00:31:16',
      respawnId: 3,
      complexity: 3,
      direction: 'top',
      endAt: '01:12:09',
      events: [
        {
          type: 'Event',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: '??????!',
        },
        {
          type: 'Event',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: 'Subaru negociate with Crusch.',
        },
        {
          type: 'Event',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: 'Willhem kills the White Whale',
        },
        {
          id: 4,
          type: 'RespawnPoint',
          timecode: '00:30:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: 'Subaru briefs his unit after killing the White Whale.',
        },
        {
          type: 'Event',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: '??!?',
        },
        {
          type: 'Death',
          timecode: '00:41:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: "Betelgeuse takes control of Subaru's body, Ferris immobilizes Subaru and Julius finishes him.",
        },
      ],
    },
    {
      id: 12,
      startAt: '00:31:16',
      respawnId: 4,
      complexity: 1,
      direction: 'top',
      endAt: '00:52:09',
      events: [
        {
          type: 'Event',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: '!???',
        },
        {
          id: 5,
          type: 'RespawnPoint',
          timecode: '00:10:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: 'Subaru talks about Rem with Emilia in the horse-drawn cart.',
        },
        {
          type: 'Event',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: 'Crusch unit is attacked by greed and gluttony bishops.',
        },
        {
          type: 'Death',
          timecode: '00:21:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: 'Subaru kills himself by sticking a knife in his throat after seeing Rem dead.',
        },
      ],
    },
    {
      id: 13,
      startAt: '00:31:16',
      respawnId: 5,
      complexity: 1,
      direction: 'top',
      endAt: '02:02:09',
      events: [
        {
          type: 'Event',
          timecode: '00:10:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: '??!!!?',
        },
        {
          id: 6,
          type: 'RespawnPoint',
          timecode: '01:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: 'Subaru successfully passes the first step of Echidna temple.',
        },
        {
          type: 'Event',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:10:00',
          description: '?!!??',
        },
        {
          type: 'Death',
          timecode: '01:31:04',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: 'Elsa rip open Subaru by surprise in the mansion.',
        },
      ],
    },
    {
      id: 14,
      startAt: '00:31:16',
      respawnId: 6,
      complexity: 1,
      direction: 'top',
      endAt: '0:42:09',
      events: [
        {
          type: 'Event',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: '???',
        },
        {
          type: 'Death',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: 'Elsa rip open Subaru by surprise in the mansion.',
        },
      ],
    },
    {
      id: 15,
      startAt: '00:31:16',
      respawnId: 6,
      complexity: 2,
      direction: 'top',
      endAt: '0:42:09',
      events: [
        {
          type: 'Event',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: '???',
        },
        {
          type: 'Death',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: "Elsa enters Beatrice's library and kills Subaru.",
        },
      ],
    },
    {
      id: 16,
      startAt: '00:31:16',
      respawnId: 6,
      complexity: 3,
      direction: 'top',
      endAt: '0:42:09',
      events: [
        {
          type: 'Event',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: '???',
        },
        {
          type: 'Death',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: 'Subaru is eatten alive by the Great Rabbit.',
        },
      ],
    },
    {
      id: 17,
      startAt: '00:31:16',
      respawnId: 6,
      complexity: 4,
      direction: 'top',
      endAt: '0:42:09',
      events: [
        {
          type: 'Event',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: '???',
        },
        {
          type: 'Death',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: "Subaru kills himself with Echidna's blessing.",
        },
      ],
    },
    {
      id: 18,
      startAt: '00:31:16',
      respawnId: 6,
      complexity: 5,
      direction: 'top',
      endAt: '0:42:09',
      events: [
        {
          type: 'Event',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: '???',
        },
        {
          type: 'Death',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: "Subaru dies in Emilia's arms inside Echidna's temple",
        },
      ],
    },
    {
      id: 19,
      startAt: '00:31:16',
      respawnId: 6,
      complexity: 6,
      direction: 'top',
      endAt: '0:42:09',
      events: [
        {
          type: 'Event',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: "Subaru tries the second step of Echidna's temple.",
        },
        {
          type: 'Death',
          timecode: '00:00:00',
          episode: '',
          episodeRelativeTC: '00:00:00',
          description: '???',
        },
      ],
    },
  ],
};
